export const toastData = [
  {
    id: 1,
    type: "success",
    title: "Success",
    message: "Project created successfully.",
    icon: "ri-checkbox-circle-fill",
    bgColor: "bg-green-50",
    textColor: "text-green-600",
    borderColor: "border-green-200",
    buttonColor: "bg-green-600",
  },
  {
    id: 2,
    type: "error",
    title: "Error",
    message: "Something went wrong. Please try again.",
    icon: "ri-close-circle-fill",
    bgColor: "bg-red-50",
    textColor: "text-red-600",
    borderColor: "border-red-200",
    buttonColor: "bg-red-600",
  },
  {
    id: 3,
    type: "warning",
    title: "Warning",
    message: "Please check all required fields.",
    icon: "ri-error-warning-fill",
    bgColor: "bg-yellow-50",
    textColor: "text-yellow-600",
    borderColor: "border-yellow-200",
    buttonColor: "bg-yellow-500",
  },
  {
    id: 4,
    type: "info",
    title: "Info",
    message: "New update is available.",
    icon: "ri-information-fill",
    bgColor: "bg-blue-50",
    textColor: "text-blue-600",
    borderColor: "border-blue-200",
    buttonColor: "bg-blue-600",
  },
];